blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogapp.urls')),
]

blogapp/urls.py
from django.urls import path
from .views import homepage,ajaxsave
app_name = 'blogapp'

urlpatterns = [
    path('homepage/',homepage),
    path('ajaxsaved/',ajaxsave,name="ajaxsaved"),
]

blogapp/models.py
from django.db import models

LOC = (
	('bengaluru','Bengaluru'),
	('hydrabad','Hydrabad'),
	('gurgaon','Gurgaon'),
)





class BlogModel(models.Model):
    title   = models.CharField(max_length=100,blank=True,null=True)
    content = models.TextField(blank=True,null=True)
    location    = models.CharField(max_length=40,default='Bengaluru',choices=LOC)
    approved = models.BooleanField(default=False)

blogapp/forms.py
from django import forms
from .models import BlogModel


class BlogModelForm(forms.ModelForm):
    class Meta:
        model= BlogModel
        fields = ['title','content','location']
        widgets = {
        'title': forms.TextInput(attrs = {'class':'form-control',}),
        'content': forms.Textarea(attrs = {'class':'form-control'}),
        'location': forms.Select(attrs={'class':'form-control'}),
        }
        
         

blogapp/views.py
from django.shortcuts import render
from .forms import BlogModelForm
from .models import BlogModel
from django.http import JsonResponse
# Create your views here.

def homepage(request):
	if request.POST:
		form = BlogModelForm(request.POST)
		form.save()
		context = {'msg':"succesfully Submitted",'form':form}
		return render(request,'homepage.html',context)
	else:
		form = BlogModelForm()
		context = {'form':form}
		return render(request,'homepage.html',context)

def ajaxsave(request):
	print(request.POST)
	print(request.POST['title'])
	BlogModel.objects.create(title=request.POST['title'],content = request.POST['textareacontent'],location = request.POST['location'])
	return JsonResponse({'message':'It worked fine'})

blogapp/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <title>Hello, world!</title>
  </head>
  <body>
    {{msg}}

    <div class="container">
      <p class="Lead badge badge-primary">
        Data will be saved once you fill form and Change the Location
      </p>

      <form method="POST">
        {% csrf_token %} {{form.as_p}}
        <!-- <button type="submit" class="btn btn-info my-2">Submit</button> -->
      </form>
      <div id="error-list"></div>
    </div>

    <script>
      document
        .getElementById("id_location")
        .addEventListener("change", save_data);

      function save_data() {
        var token = "{{csrf_token}}";
        var title = $("#id_title").val();
        var content = $("#id_content").val();
        var location = $("#id_location").val();

        $.ajax({
          type: "POST",
          headers: { "X-CSRFToken": token },
          url: "{% url 'blogapp:ajaxsaved' %}",
          data: { title: title, textareacontent: content, location: location },

          success: function (data) {
            $("#error-list").html(
              '<p style="color:brown">Form Successfully Submitted</p>'
            );
            console.log(data);
          },
          error: function (data) {},
        });
      }
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.js"
      integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blogapp/templates/junk.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a
              class="nav-link disabled"
              href="#"
              tabindex="-1"
              aria-disabled="true"
              >Disabled</a
            >
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input
            class="form-control mr-sm-2"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            Search
          </button>
        </form>
      </div>
    </nav>



    widgets = {
            'title'  : forms.TextInput(attrs={'class':'form-control','placeholder':'Enter a title'}),
            'content': forms.Textarea(attrs={'cols': 10, 'rows': 10,'class':'form-control'}),
        }

    widgets = {
        'title': forms.TextInput(attrs={'class':'form-control'}),
        'content': forms.Textarea(attrs = {'class':'form-control'}),
        'location': forms.Select(attrs={"class": "form-control"})
        }

blogapp/templates/simple.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <title>Hello, world!</title>
  </head>
  <body>





    {{msg}}
    <div class="container">
    <form method="POST">
      {% csrf_token %} {{form}}
      <button type="submit" class="my-2">Submit</button>
    </form>
    </div>







    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>